# Generated by Django 4.0.2 on 2023-06-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, verbose_name='用户名')),
                ('jaccount', models.CharField(max_length=30, unique=True, verbose_name='Jaccount')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='visitor', max_length=64)),
                ('photo', models.ImageField(default='#', upload_to='')),
                ('photo_name', models.CharField(default='visitor.jpg', max_length=120)),
                ('user', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='index.user', to_field='jaccount')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Image',
                'db_table': 'Image',
            },
        ),
    ]
