# Generated by Django 4.0.2 on 2023-06-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(default='#', upload_to='', verbose_name='Image'),
        ),
    ]
