# Generated by Django 4.0.2 on 2023-06-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_image_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='photo_name',
            new_name='photo_clean_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='photo',
        ),
        migrations.AddField(
            model_name='image',
            name='photo_clean',
            field=models.ImageField(default='#', upload_to='', verbose_name='Image_clean'),
        ),
        migrations.AddField(
            model_name='image',
            name='photo_processed',
            field=models.ImageField(default='#', upload_to='', verbose_name='Image_processed'),
        ),
        migrations.AddField(
            model_name='image',
            name='photo_processed_name',
            field=models.CharField(default='visitor_processed.jpg', max_length=120),
        ),
        migrations.AddField(
            model_name='image',
            name='text',
            field=models.CharField(default='', max_length=64),
        ),
    ]
