# Generated by Django 4.0.2 on 2023-06-09 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rename_photo_name_image_photo_clean_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='photo_processed',
        ),
    ]
