# Generated by Django 4.0.2 on 2023-06-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_remove_image_photo_processed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='photo_clean_name',
            new_name='file_time',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='photo_processed_name',
            new_name='photo_processed',
        ),
    ]
