# Generated by Django 4.0.2 on 2023-06-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_rename_photo_clean_name_image_file_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='photo_clean',
        ),
        migrations.RemoveField(
            model_name='image',
            name='photo_processed',
        ),
        migrations.AddField(
            model_name='image',
            name='photo_input',
            field=models.ImageField(default='#', upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='image',
            name='photo_output',
            field=models.CharField(default='visitor_.jpg', max_length=120),
        ),
    ]
