# Generated by Django 4.0.2 on 2023-06-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_remove_image_photo_clean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.CharField(default='none', max_length=64),
        ),
    ]
