# Generated by Django 4.0.2 on 2023-06-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='template',
            field=models.ImageField(default='#', upload_to='', verbose_name='Template'),
        ),
    ]
